### PR TITLE
increase build-number

### PR DESCRIPTION
**Pull request by looooo**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
@conda-forge/core can anyone have a look at this. There was no gcc7-PR yet, but I think dependencies are ready.

**Comment by CJ-Wright** [comment]
This is noarch, it doesn't need a gcc7 rebuild.

**Comment by looooo** [comment]
thanks, I see. But this package is not available for python3.7. So there is no noarch package available yet.
I guess merging this PR will solve this.

**Comment by CJ-Wright** [comment]
This shouldn't need a python3.7 build, since it is noarch it works with any python version. Can you not install it into a py37 env?

**Comment by looooo** [comment]
The noarch-builds failed [1]. So there is no noarch-package available yet [2], and therefore ozodf is not available for python3.7.

[1] https://circleci.com/gh/conda-forge/ezodf-feedstock/8?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
[2] https://anaconda.org/conda-forge/ezodf/files

**Comment by CJ-Wright** [comment]
Ah ok.

**Comment by CJ-Wright** [comment]
Ready for review @conda-forge/ezodf

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
Thanks @looooo!

**Pull request merged**
